// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface HeartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.HeartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double heart_rate = 1;</code>
   */
  double getHeartRate();
}
