// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_UserRecords_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_UserRecords_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_ServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_GetHealthRecordsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_GetHealthRecordsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_HeartRateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_HeartRateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_HeartRateWarning_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_HeartRateWarning_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\032\033google/proto" +
      "buf/empty.proto\"\205\001\n\013UserRecords\022\022\n\npatie" +
      "nt_id\030\001 \001(\005\022\013\n\003age\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\016" +
      "\n\006weight\030\004 \001(\001\022\016\n\006height\030\005 \001(\001\022\026\n\016close_" +
      "contacts\030\006 \003(\t\022\017\n\007address\030\007 \001(\t\"#\n\016Serve" +
      "rResponse\022\021\n\tconfirmed\030\001 \001(\t\"-\n\027GetHealt" +
      "hRecordsRequest\022\022\n\npatient_id\030\001 \001(\005\"&\n\020H" +
      "eartRateRequest\022\022\n\nheart_rate\030\001 \001(\001\"#\n\020H" +
      "eartRateWarning\022\017\n\007message\030\001 \001(\t2\367\001\n\nMon" +
      "itoring\022E\n\016SetUserRecords\022\025.service3.Use" +
      "rRecords\032\030.service3.ServerResponse\"\000(\001\022P" +
      "\n\020GetHealthRecords\022!.service3.GetHealthR" +
      "ecordsRequest\032\025.service3.UserRecords\"\0000\001" +
      "\022P\n\020MonitorHeartRate\022\032.service3.HeartRat" +
      "eRequest\032\032.service3.HeartRateWarning\"\000(\001" +
      "0\001B\035\n\013ds.service3B\014Service3ImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_service3_UserRecords_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_UserRecords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_UserRecords_descriptor,
        new java.lang.String[] { "PatientId", "Age", "Name", "Weight", "Height", "CloseContacts", "Address", });
    internal_static_service3_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_ServerResponse_descriptor,
        new java.lang.String[] { "Confirmed", });
    internal_static_service3_GetHealthRecordsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_GetHealthRecordsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_GetHealthRecordsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_service3_HeartRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_HeartRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_HeartRateRequest_descriptor,
        new java.lang.String[] { "HeartRate", });
    internal_static_service3_HeartRateWarning_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_HeartRateWarning_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_HeartRateWarning_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
