// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface UserRecordsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.UserRecords)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patient_id = 1;</code>
   */
  int getPatientId();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double weight = 4;</code>
   */
  double getWeight();

  /**
   * <code>double height = 5;</code>
   */
  double getHeight();

  /**
   * <code>repeated string close_contacts = 6;</code>
   */
  java.util.List<java.lang.String>
      getCloseContactsList();
  /**
   * <code>repeated string close_contacts = 6;</code>
   */
  int getCloseContactsCount();
  /**
   * <code>repeated string close_contacts = 6;</code>
   */
  java.lang.String getCloseContacts(int index);
  /**
   * <code>repeated string close_contacts = 6;</code>
   */
  com.google.protobuf.ByteString
      getCloseContactsBytes(int index);

  /**
   * <code>string address = 7;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 7;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
