// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

public interface AverageStepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AverageStepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service1.Periods period = 1;</code>
   */
  int getPeriodValue();
  /**
   * <code>.service1.Periods period = 1;</code>
   */
  sw.stepCounter.service1.Periods getPeriod();
}
