// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

/**
 * <pre>
 * </pre>
 *
 * Protobuf enum {@code service1.Periods}
 */
public enum Periods
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LAST_DAY = 0;</code>
   */
  LAST_DAY(0),
  /**
   * <code>LAST_5_DAYS = 1;</code>
   */
  LAST_5_DAYS(1),
  /**
   * <code>LAST_10_DAYS = 2;</code>
   */
  LAST_10_DAYS(2),
  /**
   * <code>LAST_30_DAYS = 3;</code>
   */
  LAST_30_DAYS(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LAST_DAY = 0;</code>
   */
  public static final int LAST_DAY_VALUE = 0;
  /**
   * <code>LAST_5_DAYS = 1;</code>
   */
  public static final int LAST_5_DAYS_VALUE = 1;
  /**
   * <code>LAST_10_DAYS = 2;</code>
   */
  public static final int LAST_10_DAYS_VALUE = 2;
  /**
   * <code>LAST_30_DAYS = 3;</code>
   */
  public static final int LAST_30_DAYS_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Periods valueOf(int value) {
    return forNumber(value);
  }

  public static Periods forNumber(int value) {
    switch (value) {
      case 0: return LAST_DAY;
      case 1: return LAST_5_DAYS;
      case 2: return LAST_10_DAYS;
      case 3: return LAST_30_DAYS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Periods>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Periods> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Periods>() {
          public Periods findValueByNumber(int number) {
            return Periods.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return sw.stepCounter.service1.stepCounterImpl.getDescriptor().getEnumTypes().get(0);
  }

  private static final Periods[] VALUES = values();

  public static Periods valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Periods(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:service1.Periods)
}

