// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

public final class stepCounterImpl {
  private stepCounterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_HourlyStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_HourlyStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_HourlyStepCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_HourlyStepCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepGoal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepGoal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepGoalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepGoalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\032\033google/proto" +
      "buf/empty.proto\"\035\n\014StepsRequest\022\r\n\005steps" +
      "\030\001 \001(\005\"\032\n\tStepCount\022\r\n\005count\030\001 \001(\005\":\n\021Ho" +
      "urlyStepRequest\022%\n\tweek_days\030\001 \001(\0162\022.ser" +
      "vice1.WeekDays\"`\n\017HourlyStepCount\022\025\n\rave" +
      "rage_steps\030\001 \001(\005\022%\n\tweek_days\030\002 \001(\0162\022.se" +
      "rvice1.WeekDays\022\017\n\007message\030\003 \001(\t\"\030\n\010Step" +
      "Goal\022\014\n\004goal\030\001 \001(\005\"B\n\020StepGoalResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\014\n\004left\030\002 \001(\005\022\017\n\007message" +
      "\030\003 \001(\t*M\n\010WeekDays\022\014\n\010LAST_DAY\020\000\022\017\n\013LAST" +
      "_5_DAYS\020\001\022\020\n\014LAST_10_DAYS\020\002\022\020\n\014LAST_30_D" +
      "AYS\020\0032\244\002\n\013StepCounter\022<\n\tSendSteps\022\026.ser" +
      "vice1.StepsRequest\032\023.service1.StepCount\"" +
      "\000(\001\022A\n\020GetLastHourSteps\022\026.google.protobu" +
      "f.Empty\032\023.service1.StepCount\"\000\022Q\n\025GetAve" +
      "rageHourlySteps\022\033.service1.HourlyStepReq" +
      "uest\032\031.service1.HourlyStepCount\"\000\022A\n\013Set" +
      "StepGoal\022\022.service1.StepGoal\032\032.service1." +
      "StepGoalResponse\"\0000\001B,\n\027sw.stepCounter.s" +
      "ervice1B\017stepCounterImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_service1_StepsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_StepsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepsRequest_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_service1_StepCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_StepCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepCount_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_service1_HourlyStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_HourlyStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_HourlyStepRequest_descriptor,
        new java.lang.String[] { "WeekDays", });
    internal_static_service1_HourlyStepCount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_HourlyStepCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_HourlyStepCount_descriptor,
        new java.lang.String[] { "AverageSteps", "WeekDays", "Message", });
    internal_static_service1_StepGoal_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_StepGoal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepGoal_descriptor,
        new java.lang.String[] { "Goal", });
    internal_static_service1_StepGoalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_StepGoalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepGoalResponse_descriptor,
        new java.lang.String[] { "Success", "Left", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
