// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

public interface StepGoalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.StepGoal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 goal = 1;</code>
   */
  int getGoal();
}
