// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

public interface StepsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.StepsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 steps = 1;</code>
   */
  int getSteps();
}
