// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

public interface StepCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.StepCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   */
  int getCount();
}
