// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

public final class stepCounterImpl {
  private stepCounterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_HourlyStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_HourlyStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_HourlyStepCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_HourlyStepCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepGoal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepGoal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_StepGoalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_StepGoalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\032\033google/proto" +
      "buf/empty.proto\"\035\n\014StepsRequest\022\r\n\005steps" +
      "\030\001 \001(\005\"\032\n\tStepCount\022\r\n\005count\030\001 \001(\005\"L\n\021Ho" +
      "urlyStepRequest\022\014\n\004hour\030\001 \001(\005\022)\n\013time_pe" +
      "riod\030\002 \001(\0162\024.service1.TimePeriod\"d\n\017Hour" +
      "lyStepCount\022\025\n\raverage_steps\030\001 \001(\005\022)\n\013ti" +
      "me_period\030\002 \001(\0162\024.service1.TimePeriod\022\017\n" +
      "\007message\030\003 \001(\t\"\030\n\010StepGoal\022\014\n\004goal\030\001 \001(\005" +
      "\"#\n\020StepGoalResponse\022\017\n\007success\030\001 \001(\010*:\n" +
      "\nTimePeriod\022\r\n\tLAST_WEEK\020\000\022\016\n\nLAST_MONTH" +
      "\020\001\022\r\n\tLAST_YEAR\020\0022\247\002\n\013StepCounter\022?\n\tSen" +
      "dSteps\022\026.service1.StepsRequest\032\026.google." +
      "protobuf.Empty\"\000(\001\022A\n\020GetLastHourSteps\022\026" +
      ".google.protobuf.Empty\032\023.service1.StepCo" +
      "unt\"\000\022S\n\025GetAverageHourlySteps\022\033.service" +
      "1.HourlyStepRequest\032\031.service1.HourlySte" +
      "pCount\"\000(\001\022?\n\013SetStepGoal\022\022.service1.Ste" +
      "pGoal\032\032.service1.StepGoalResponse\"\000B,\n\027s" +
      "w.stepCounter.service1B\017stepCounterImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_service1_StepsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_StepsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepsRequest_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_service1_StepCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_StepCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepCount_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_service1_HourlyStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_HourlyStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_HourlyStepRequest_descriptor,
        new java.lang.String[] { "Hour", "TimePeriod", });
    internal_static_service1_HourlyStepCount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_HourlyStepCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_HourlyStepCount_descriptor,
        new java.lang.String[] { "AverageSteps", "TimePeriod", "Message", });
    internal_static_service1_StepGoal_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_StepGoal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepGoal_descriptor,
        new java.lang.String[] { "Goal", });
    internal_static_service1_StepGoalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_StepGoalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_StepGoalResponse_descriptor,
        new java.lang.String[] { "Success", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
