// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

/**
 * <pre>
 * Defined the TimePeriod enumeration in a separate file or message to ensure consistency
 * </pre>
 *
 * Protobuf enum {@code service1.TimePeriod}
 */
public enum TimePeriod
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LAST_WEEK = 0;</code>
   */
  LAST_WEEK(0),
  /**
   * <code>LAST_MONTH = 1;</code>
   */
  LAST_MONTH(1),
  /**
   * <code>LAST_YEAR = 2;</code>
   */
  LAST_YEAR(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LAST_WEEK = 0;</code>
   */
  public static final int LAST_WEEK_VALUE = 0;
  /**
   * <code>LAST_MONTH = 1;</code>
   */
  public static final int LAST_MONTH_VALUE = 1;
  /**
   * <code>LAST_YEAR = 2;</code>
   */
  public static final int LAST_YEAR_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TimePeriod valueOf(int value) {
    return forNumber(value);
  }

  public static TimePeriod forNumber(int value) {
    switch (value) {
      case 0: return LAST_WEEK;
      case 1: return LAST_MONTH;
      case 2: return LAST_YEAR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TimePeriod>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TimePeriod> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TimePeriod>() {
          public TimePeriod findValueByNumber(int number) {
            return TimePeriod.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return sw.stepCounter.service1.stepCounterImpl.getDescriptor().getEnumTypes().get(0);
  }

  private static final TimePeriod[] VALUES = values();

  public static TimePeriod valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TimePeriod(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:service1.TimePeriod)
}

