// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package sw.stepCounter.service1;

/**
 * <pre>
 * </pre>
 *
 * Protobuf enum {@code service1.WeekDays}
 */
public enum WeekDays
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MONDAY = 0;</code>
   */
  MONDAY(0),
  /**
   * <code>TUESDAY = 1;</code>
   */
  TUESDAY(1),
  /**
   * <code>WEDNESDAY = 2;</code>
   */
  WEDNESDAY(2),
  /**
   * <code>THURSDAY = 3;</code>
   */
  THURSDAY(3),
  /**
   * <code>FRIDAY = 4;</code>
   */
  FRIDAY(4),
  /**
   * <code>SATURDAY = 5;</code>
   */
  SATURDAY(5),
  /**
   * <code>SUNDAY = 6;</code>
   */
  SUNDAY(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MONDAY = 0;</code>
   */
  public static final int MONDAY_VALUE = 0;
  /**
   * <code>TUESDAY = 1;</code>
   */
  public static final int TUESDAY_VALUE = 1;
  /**
   * <code>WEDNESDAY = 2;</code>
   */
  public static final int WEDNESDAY_VALUE = 2;
  /**
   * <code>THURSDAY = 3;</code>
   */
  public static final int THURSDAY_VALUE = 3;
  /**
   * <code>FRIDAY = 4;</code>
   */
  public static final int FRIDAY_VALUE = 4;
  /**
   * <code>SATURDAY = 5;</code>
   */
  public static final int SATURDAY_VALUE = 5;
  /**
   * <code>SUNDAY = 6;</code>
   */
  public static final int SUNDAY_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WeekDays valueOf(int value) {
    return forNumber(value);
  }

  public static WeekDays forNumber(int value) {
    switch (value) {
      case 0: return MONDAY;
      case 1: return TUESDAY;
      case 2: return WEDNESDAY;
      case 3: return THURSDAY;
      case 4: return FRIDAY;
      case 5: return SATURDAY;
      case 6: return SUNDAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WeekDays>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WeekDays> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WeekDays>() {
          public WeekDays findValueByNumber(int number) {
            return WeekDays.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return sw.stepCounter.service1.stepCounterImpl.getDescriptor().getEnumTypes().get(0);
  }

  private static final WeekDays[] VALUES = values();

  public static WeekDays valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WeekDays(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:service1.WeekDays)
}

