// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public interface EmergencyContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.EmergencyContact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string phone = 2;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 2;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
