// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

/**
 * Protobuf type {@code service3.GetHealthRecordsResponse}
 */
public  final class GetHealthRecordsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.GetHealthRecordsResponse)
    GetHealthRecordsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetHealthRecordsResponse.newBuilder() to construct.
  private GetHealthRecordsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetHealthRecordsResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetHealthRecordsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            sw.Monitoring.service3.UserRecords.Builder subBuilder = null;
            if (userRecords_ != null) {
              subBuilder = userRecords_.toBuilder();
            }
            userRecords_ = input.readMessage(sw.Monitoring.service3.UserRecords.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userRecords_);
              userRecords_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sw.Monitoring.service3.MonitorImpl.internal_static_service3_GetHealthRecordsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sw.Monitoring.service3.MonitorImpl.internal_static_service3_GetHealthRecordsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sw.Monitoring.service3.GetHealthRecordsResponse.class, sw.Monitoring.service3.GetHealthRecordsResponse.Builder.class);
  }

  public static final int USER_RECORDS_FIELD_NUMBER = 1;
  private sw.Monitoring.service3.UserRecords userRecords_;
  /**
   * <code>.service3.UserRecords user_records = 1;</code>
   */
  public boolean hasUserRecords() {
    return userRecords_ != null;
  }
  /**
   * <code>.service3.UserRecords user_records = 1;</code>
   */
  public sw.Monitoring.service3.UserRecords getUserRecords() {
    return userRecords_ == null ? sw.Monitoring.service3.UserRecords.getDefaultInstance() : userRecords_;
  }
  /**
   * <code>.service3.UserRecords user_records = 1;</code>
   */
  public sw.Monitoring.service3.UserRecordsOrBuilder getUserRecordsOrBuilder() {
    return getUserRecords();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userRecords_ != null) {
      output.writeMessage(1, getUserRecords());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userRecords_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserRecords());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sw.Monitoring.service3.GetHealthRecordsResponse)) {
      return super.equals(obj);
    }
    sw.Monitoring.service3.GetHealthRecordsResponse other = (sw.Monitoring.service3.GetHealthRecordsResponse) obj;

    boolean result = true;
    result = result && (hasUserRecords() == other.hasUserRecords());
    if (hasUserRecords()) {
      result = result && getUserRecords()
          .equals(other.getUserRecords());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserRecords()) {
      hash = (37 * hash) + USER_RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getUserRecords().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sw.Monitoring.service3.GetHealthRecordsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sw.Monitoring.service3.GetHealthRecordsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.GetHealthRecordsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.GetHealthRecordsResponse)
      sw.Monitoring.service3.GetHealthRecordsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sw.Monitoring.service3.MonitorImpl.internal_static_service3_GetHealthRecordsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sw.Monitoring.service3.MonitorImpl.internal_static_service3_GetHealthRecordsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sw.Monitoring.service3.GetHealthRecordsResponse.class, sw.Monitoring.service3.GetHealthRecordsResponse.Builder.class);
    }

    // Construct using sw.Monitoring.service3.GetHealthRecordsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userRecordsBuilder_ == null) {
        userRecords_ = null;
      } else {
        userRecords_ = null;
        userRecordsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sw.Monitoring.service3.MonitorImpl.internal_static_service3_GetHealthRecordsResponse_descriptor;
    }

    @java.lang.Override
    public sw.Monitoring.service3.GetHealthRecordsResponse getDefaultInstanceForType() {
      return sw.Monitoring.service3.GetHealthRecordsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sw.Monitoring.service3.GetHealthRecordsResponse build() {
      sw.Monitoring.service3.GetHealthRecordsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sw.Monitoring.service3.GetHealthRecordsResponse buildPartial() {
      sw.Monitoring.service3.GetHealthRecordsResponse result = new sw.Monitoring.service3.GetHealthRecordsResponse(this);
      if (userRecordsBuilder_ == null) {
        result.userRecords_ = userRecords_;
      } else {
        result.userRecords_ = userRecordsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sw.Monitoring.service3.GetHealthRecordsResponse) {
        return mergeFrom((sw.Monitoring.service3.GetHealthRecordsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sw.Monitoring.service3.GetHealthRecordsResponse other) {
      if (other == sw.Monitoring.service3.GetHealthRecordsResponse.getDefaultInstance()) return this;
      if (other.hasUserRecords()) {
        mergeUserRecords(other.getUserRecords());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sw.Monitoring.service3.GetHealthRecordsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sw.Monitoring.service3.GetHealthRecordsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private sw.Monitoring.service3.UserRecords userRecords_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sw.Monitoring.service3.UserRecords, sw.Monitoring.service3.UserRecords.Builder, sw.Monitoring.service3.UserRecordsOrBuilder> userRecordsBuilder_;
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public boolean hasUserRecords() {
      return userRecordsBuilder_ != null || userRecords_ != null;
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public sw.Monitoring.service3.UserRecords getUserRecords() {
      if (userRecordsBuilder_ == null) {
        return userRecords_ == null ? sw.Monitoring.service3.UserRecords.getDefaultInstance() : userRecords_;
      } else {
        return userRecordsBuilder_.getMessage();
      }
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public Builder setUserRecords(sw.Monitoring.service3.UserRecords value) {
      if (userRecordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userRecords_ = value;
        onChanged();
      } else {
        userRecordsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public Builder setUserRecords(
        sw.Monitoring.service3.UserRecords.Builder builderForValue) {
      if (userRecordsBuilder_ == null) {
        userRecords_ = builderForValue.build();
        onChanged();
      } else {
        userRecordsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public Builder mergeUserRecords(sw.Monitoring.service3.UserRecords value) {
      if (userRecordsBuilder_ == null) {
        if (userRecords_ != null) {
          userRecords_ =
            sw.Monitoring.service3.UserRecords.newBuilder(userRecords_).mergeFrom(value).buildPartial();
        } else {
          userRecords_ = value;
        }
        onChanged();
      } else {
        userRecordsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public Builder clearUserRecords() {
      if (userRecordsBuilder_ == null) {
        userRecords_ = null;
        onChanged();
      } else {
        userRecords_ = null;
        userRecordsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public sw.Monitoring.service3.UserRecords.Builder getUserRecordsBuilder() {
      
      onChanged();
      return getUserRecordsFieldBuilder().getBuilder();
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    public sw.Monitoring.service3.UserRecordsOrBuilder getUserRecordsOrBuilder() {
      if (userRecordsBuilder_ != null) {
        return userRecordsBuilder_.getMessageOrBuilder();
      } else {
        return userRecords_ == null ?
            sw.Monitoring.service3.UserRecords.getDefaultInstance() : userRecords_;
      }
    }
    /**
     * <code>.service3.UserRecords user_records = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sw.Monitoring.service3.UserRecords, sw.Monitoring.service3.UserRecords.Builder, sw.Monitoring.service3.UserRecordsOrBuilder> 
        getUserRecordsFieldBuilder() {
      if (userRecordsBuilder_ == null) {
        userRecordsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sw.Monitoring.service3.UserRecords, sw.Monitoring.service3.UserRecords.Builder, sw.Monitoring.service3.UserRecordsOrBuilder>(
                getUserRecords(),
                getParentForChildren(),
                isClean());
        userRecords_ = null;
      }
      return userRecordsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.GetHealthRecordsResponse)
  }

  // @@protoc_insertion_point(class_scope:service3.GetHealthRecordsResponse)
  private static final sw.Monitoring.service3.GetHealthRecordsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sw.Monitoring.service3.GetHealthRecordsResponse();
  }

  public static sw.Monitoring.service3.GetHealthRecordsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetHealthRecordsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetHealthRecordsResponse>() {
    @java.lang.Override
    public GetHealthRecordsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetHealthRecordsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetHealthRecordsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetHealthRecordsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sw.Monitoring.service3.GetHealthRecordsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

