// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public interface GetHealthRecordsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.GetHealthRecordsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patient_id = 1;</code>
   */
  int getPatientId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  public sw.Monitoring.service3.GetHealthRecordsRequest.ModeCase getModeCase();
}
