// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public interface GetHealthRecordsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.GetHealthRecordsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service3.PatientID patient_id = 1;</code>
   */
  boolean hasPatientId();
  /**
   * <code>.service3.PatientID patient_id = 1;</code>
   */
  sw.Monitoring.service3.PatientID getPatientId();
  /**
   * <code>.service3.PatientID patient_id = 1;</code>
   */
  sw.Monitoring.service3.PatientIDOrBuilder getPatientIdOrBuilder();
}
