// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public interface GetHealthRecordsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.GetHealthRecordsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service3.UserRecords user_records = 1;</code>
   */
  boolean hasUserRecords();
  /**
   * <code>.service3.UserRecords user_records = 1;</code>
   */
  sw.Monitoring.service3.UserRecords getUserRecords();
  /**
   * <code>.service3.UserRecords user_records = 1;</code>
   */
  sw.Monitoring.service3.UserRecordsOrBuilder getUserRecordsOrBuilder();
}
