// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

/**
 * Protobuf type {@code service3.HeartRateRequest}
 */
public  final class HeartRateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.HeartRateRequest)
    HeartRateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartRateRequest.newBuilder() to construct.
  private HeartRateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartRateRequest() {
    heartRate_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeartRateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            heartRate_ = input.readDouble();
            break;
          }
          case 16: {
            modeCase_ = 2;
            mode_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            modeCase_ = 3;
            mode_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sw.Monitoring.service3.MonitorImpl.internal_static_service3_HeartRateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sw.Monitoring.service3.MonitorImpl.internal_static_service3_HeartRateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sw.Monitoring.service3.HeartRateRequest.class, sw.Monitoring.service3.HeartRateRequest.Builder.class);
  }

  private int modeCase_ = 0;
  private java.lang.Object mode_;
  public enum ModeCase
      implements com.google.protobuf.Internal.EnumLite {
    PATIENT_ID(2),
    NAME(3),
    MODE_NOT_SET(0);
    private final int value;
    private ModeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ModeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ModeCase forNumber(int value) {
      switch (value) {
        case 2: return PATIENT_ID;
        case 3: return NAME;
        case 0: return MODE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ModeCase
  getModeCase() {
    return ModeCase.forNumber(
        modeCase_);
  }

  public static final int HEART_RATE_FIELD_NUMBER = 1;
  private double heartRate_;
  /**
   * <code>double heart_rate = 1;</code>
   */
  public double getHeartRate() {
    return heartRate_;
  }

  public static final int PATIENT_ID_FIELD_NUMBER = 2;
  /**
   * <code>int32 patient_id = 2;</code>
   */
  public int getPatientId() {
    if (modeCase_ == 2) {
      return (java.lang.Integer) mode_;
    }
    return 0;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  /**
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = "";
    if (modeCase_ == 3) {
      ref = mode_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (modeCase_ == 3) {
        mode_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = "";
    if (modeCase_ == 3) {
      ref = mode_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (modeCase_ == 3) {
        mode_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (heartRate_ != 0D) {
      output.writeDouble(1, heartRate_);
    }
    if (modeCase_ == 2) {
      output.writeInt32(
          2, (int)((java.lang.Integer) mode_));
    }
    if (modeCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (heartRate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, heartRate_);
    }
    if (modeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            2, (int)((java.lang.Integer) mode_));
    }
    if (modeCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sw.Monitoring.service3.HeartRateRequest)) {
      return super.equals(obj);
    }
    sw.Monitoring.service3.HeartRateRequest other = (sw.Monitoring.service3.HeartRateRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getHeartRate())
        == java.lang.Double.doubleToLongBits(
            other.getHeartRate()));
    result = result && getModeCase().equals(
        other.getModeCase());
    if (!result) return false;
    switch (modeCase_) {
      case 2:
        result = result && (getPatientId()
            == other.getPatientId());
        break;
      case 3:
        result = result && getName()
            .equals(other.getName());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEART_RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHeartRate()));
    switch (modeCase_) {
      case 2:
        hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPatientId();
        break;
      case 3:
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sw.Monitoring.service3.HeartRateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sw.Monitoring.service3.HeartRateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.HeartRateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.HeartRateRequest)
      sw.Monitoring.service3.HeartRateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sw.Monitoring.service3.MonitorImpl.internal_static_service3_HeartRateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sw.Monitoring.service3.MonitorImpl.internal_static_service3_HeartRateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sw.Monitoring.service3.HeartRateRequest.class, sw.Monitoring.service3.HeartRateRequest.Builder.class);
    }

    // Construct using sw.Monitoring.service3.HeartRateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      heartRate_ = 0D;

      modeCase_ = 0;
      mode_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sw.Monitoring.service3.MonitorImpl.internal_static_service3_HeartRateRequest_descriptor;
    }

    @java.lang.Override
    public sw.Monitoring.service3.HeartRateRequest getDefaultInstanceForType() {
      return sw.Monitoring.service3.HeartRateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sw.Monitoring.service3.HeartRateRequest build() {
      sw.Monitoring.service3.HeartRateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sw.Monitoring.service3.HeartRateRequest buildPartial() {
      sw.Monitoring.service3.HeartRateRequest result = new sw.Monitoring.service3.HeartRateRequest(this);
      result.heartRate_ = heartRate_;
      if (modeCase_ == 2) {
        result.mode_ = mode_;
      }
      if (modeCase_ == 3) {
        result.mode_ = mode_;
      }
      result.modeCase_ = modeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sw.Monitoring.service3.HeartRateRequest) {
        return mergeFrom((sw.Monitoring.service3.HeartRateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sw.Monitoring.service3.HeartRateRequest other) {
      if (other == sw.Monitoring.service3.HeartRateRequest.getDefaultInstance()) return this;
      if (other.getHeartRate() != 0D) {
        setHeartRate(other.getHeartRate());
      }
      switch (other.getModeCase()) {
        case PATIENT_ID: {
          setPatientId(other.getPatientId());
          break;
        }
        case NAME: {
          modeCase_ = 3;
          mode_ = other.mode_;
          onChanged();
          break;
        }
        case MODE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sw.Monitoring.service3.HeartRateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sw.Monitoring.service3.HeartRateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int modeCase_ = 0;
    private java.lang.Object mode_;
    public ModeCase
        getModeCase() {
      return ModeCase.forNumber(
          modeCase_);
    }

    public Builder clearMode() {
      modeCase_ = 0;
      mode_ = null;
      onChanged();
      return this;
    }


    private double heartRate_ ;
    /**
     * <code>double heart_rate = 1;</code>
     */
    public double getHeartRate() {
      return heartRate_;
    }
    /**
     * <code>double heart_rate = 1;</code>
     */
    public Builder setHeartRate(double value) {
      
      heartRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double heart_rate = 1;</code>
     */
    public Builder clearHeartRate() {
      
      heartRate_ = 0D;
      onChanged();
      return this;
    }

    /**
     * <code>int32 patient_id = 2;</code>
     */
    public int getPatientId() {
      if (modeCase_ == 2) {
        return (java.lang.Integer) mode_;
      }
      return 0;
    }
    /**
     * <code>int32 patient_id = 2;</code>
     */
    public Builder setPatientId(int value) {
      modeCase_ = 2;
      mode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 patient_id = 2;</code>
     */
    public Builder clearPatientId() {
      if (modeCase_ == 2) {
        modeCase_ = 0;
        mode_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = "";
      if (modeCase_ == 3) {
        ref = mode_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (modeCase_ == 3) {
          mode_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = "";
      if (modeCase_ == 3) {
        ref = mode_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (modeCase_ == 3) {
          mode_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  modeCase_ = 3;
      mode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      if (modeCase_ == 3) {
        modeCase_ = 0;
        mode_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      modeCase_ = 3;
      mode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.HeartRateRequest)
  }

  // @@protoc_insertion_point(class_scope:service3.HeartRateRequest)
  private static final sw.Monitoring.service3.HeartRateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sw.Monitoring.service3.HeartRateRequest();
  }

  public static sw.Monitoring.service3.HeartRateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartRateRequest>
      PARSER = new com.google.protobuf.AbstractParser<HeartRateRequest>() {
    @java.lang.Override
    public HeartRateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeartRateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeartRateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartRateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sw.Monitoring.service3.HeartRateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

