// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public interface HeartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.HeartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double heart_rate = 1;</code>
   */
  double getHeartRate();

  /**
   * <code>int32 patient_id = 2;</code>
   */
  int getPatientId();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  public sw.Monitoring.service3.HeartRateRequest.ModeCase getModeCase();
}
