// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public interface HeartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.HeartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double heart_rate = 1;</code>
   */
  double getHeartRate();

  /**
   * <code>.service3.PatientID patient_id = 2;</code>
   */
  boolean hasPatientId();
  /**
   * <code>.service3.PatientID patient_id = 2;</code>
   */
  sw.Monitoring.service3.PatientID getPatientId();
  /**
   * <code>.service3.PatientID patient_id = 2;</code>
   */
  sw.Monitoring.service3.PatientIDOrBuilder getPatientIdOrBuilder();
}
