// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package sw.Monitoring.service3;

public final class MonitorImpl {
  private MonitorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_UserRecords_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_UserRecords_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_EmergencyContact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_EmergencyContact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_ServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_GetHealthRecordsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_GetHealthRecordsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_GetHealthRecordsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_GetHealthRecordsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PatientID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PatientID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_HeartRateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_HeartRateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_HeartRateWarning_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_HeartRateWarning_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\032\033google/proto" +
      "buf/empty.proto\"\233\001\n\013UserRecords\022\022\n\npatie" +
      "nt_id\030\001 \001(\005\022\013\n\003age\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\016" +
      "\n\006weight\030\004 \001(\001\022\016\n\006height\030\005 \001(\001\022\017\n\007addres" +
      "s\030\006 \001(\t\022,\n\010Contacts\030\007 \003(\0132\032.service3.Eme" +
      "rgencyContact\"/\n\020EmergencyContact\022\014\n\004nam" +
      "e\030\001 \001(\t\022\r\n\005phone\030\002 \001(\t\"#\n\016ServerResponse" +
      "\022\021\n\tconfirmed\030\001 \001(\t\"B\n\027GetHealthRecordsR" +
      "equest\022\'\n\npatient_id\030\001 \001(\0132\023.service3.Pa" +
      "tientID\"G\n\030GetHealthRecordsResponse\022+\n\014u" +
      "ser_records\030\001 \001(\0132\025.service3.UserRecords" +
      "\"\037\n\tPatientID\022\022\n\npatient_id\030\001 \001(\005\"O\n\020Hea" +
      "rtRateRequest\022\022\n\nheart_rate\030\001 \001(\001\022\'\n\npat" +
      "ient_id\030\002 \001(\0132\023.service3.PatientID\"#\n\020He" +
      "artRateWarning\022\017\n\007message\030\001 \001(\t2\200\002\n\nMoni" +
      "toring\022C\n\016SetUserRecords\022\025.service3.User" +
      "Records\032\030.service3.ServerResponse\"\000\022[\n\020G" +
      "etHealthRecords\022!.service3.GetHealthReco" +
      "rdsRequest\032\".service3.GetHealthRecordsRe" +
      "sponse\"\000\022P\n\020MonitorHeartRate\022\032.service3." +
      "HeartRateRequest\032\032.service3.HeartRateWar" +
      "ning\"\000(\0010\001B\'\n\026sw.Monitoring.service3B\013Mo" +
      "nitorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_service3_UserRecords_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_UserRecords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_UserRecords_descriptor,
        new java.lang.String[] { "PatientId", "Age", "Name", "Weight", "Height", "Address", "Contacts", });
    internal_static_service3_EmergencyContact_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_EmergencyContact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_EmergencyContact_descriptor,
        new java.lang.String[] { "Name", "Phone", });
    internal_static_service3_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_ServerResponse_descriptor,
        new java.lang.String[] { "Confirmed", });
    internal_static_service3_GetHealthRecordsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_GetHealthRecordsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_GetHealthRecordsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_service3_GetHealthRecordsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_GetHealthRecordsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_GetHealthRecordsResponse_descriptor,
        new java.lang.String[] { "UserRecords", });
    internal_static_service3_PatientID_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3_PatientID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PatientID_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_service3_HeartRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service3_HeartRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_HeartRateRequest_descriptor,
        new java.lang.String[] { "HeartRate", "PatientId", });
    internal_static_service3_HeartRateWarning_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_service3_HeartRateWarning_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_HeartRateWarning_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
