// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package sw.Reminder.service2;

public interface ServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmed = 1;</code>
   */
  java.lang.String getConfirmed();
  /**
   * <code>string confirmed = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmedBytes();
}
