// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package sw.Reminder.service2;

public interface TaskReminderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.TaskReminder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>string task_name = 2;</code>
   */
  java.lang.String getTaskName();
  /**
   * <code>string task_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskNameBytes();
}
