// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package sw.Reminder.service2;

public interface TaskCompleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.TaskComplete)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_name = 1;</code>
   */
  java.lang.String getTaskName();
  /**
   * <code>string task_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaskNameBytes();
}
