// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package sw.Reminder.service2;

/**
 * <pre>
 *Change this to save data time instead in64 time!!!!
 * Reminder request and response messages
 * </pre>
 *
 * Protobuf type {@code service2.TaskReminder}
 */
public  final class TaskReminder extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service2.TaskReminder)
    TaskReminderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskReminder.newBuilder() to construct.
  private TaskReminder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskReminder() {
    dateTime_ = "";
    taskName_ = "";
    type_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskReminder(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dateTime_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            taskName_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sw.Reminder.service2.taskReminderImpl.internal_static_service2_TaskReminder_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sw.Reminder.service2.taskReminderImpl.internal_static_service2_TaskReminder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sw.Reminder.service2.TaskReminder.class, sw.Reminder.service2.TaskReminder.Builder.class);
  }

  public static final int DATE_TIME_FIELD_NUMBER = 1;
  private volatile java.lang.Object dateTime_;
  /**
   * <code>string date_time = 1;</code>
   */
  public java.lang.String getDateTime() {
    java.lang.Object ref = dateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string date_time = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDateTimeBytes() {
    java.lang.Object ref = dateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object taskName_;
  /**
   * <code>string task_name = 2;</code>
   */
  public java.lang.String getTaskName() {
    java.lang.Object ref = taskName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskName_ = s;
      return s;
    }
  }
  /**
   * <code>string task_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTaskNameBytes() {
    java.lang.Object ref = taskName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.service2.Type type = 3;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.service2.Type type = 3;</code>
   */
  public sw.Reminder.service2.Type getType() {
    @SuppressWarnings("deprecation")
    sw.Reminder.service2.Type result = sw.Reminder.service2.Type.valueOf(type_);
    return result == null ? sw.Reminder.service2.Type.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDateTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dateTime_);
    }
    if (!getTaskNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskName_);
    }
    if (type_ != sw.Reminder.service2.Type.STANDART.getNumber()) {
      output.writeEnum(3, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDateTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dateTime_);
    }
    if (!getTaskNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskName_);
    }
    if (type_ != sw.Reminder.service2.Type.STANDART.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sw.Reminder.service2.TaskReminder)) {
      return super.equals(obj);
    }
    sw.Reminder.service2.TaskReminder other = (sw.Reminder.service2.TaskReminder) obj;

    boolean result = true;
    result = result && getDateTime()
        .equals(other.getDateTime());
    result = result && getTaskName()
        .equals(other.getTaskName());
    result = result && type_ == other.type_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getDateTime().hashCode();
    hash = (37 * hash) + TASK_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTaskName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sw.Reminder.service2.TaskReminder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sw.Reminder.service2.TaskReminder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sw.Reminder.service2.TaskReminder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sw.Reminder.service2.TaskReminder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sw.Reminder.service2.TaskReminder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Change this to save data time instead in64 time!!!!
   * Reminder request and response messages
   * </pre>
   *
   * Protobuf type {@code service2.TaskReminder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service2.TaskReminder)
      sw.Reminder.service2.TaskReminderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sw.Reminder.service2.taskReminderImpl.internal_static_service2_TaskReminder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sw.Reminder.service2.taskReminderImpl.internal_static_service2_TaskReminder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sw.Reminder.service2.TaskReminder.class, sw.Reminder.service2.TaskReminder.Builder.class);
    }

    // Construct using sw.Reminder.service2.TaskReminder.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dateTime_ = "";

      taskName_ = "";

      type_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sw.Reminder.service2.taskReminderImpl.internal_static_service2_TaskReminder_descriptor;
    }

    @java.lang.Override
    public sw.Reminder.service2.TaskReminder getDefaultInstanceForType() {
      return sw.Reminder.service2.TaskReminder.getDefaultInstance();
    }

    @java.lang.Override
    public sw.Reminder.service2.TaskReminder build() {
      sw.Reminder.service2.TaskReminder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sw.Reminder.service2.TaskReminder buildPartial() {
      sw.Reminder.service2.TaskReminder result = new sw.Reminder.service2.TaskReminder(this);
      result.dateTime_ = dateTime_;
      result.taskName_ = taskName_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sw.Reminder.service2.TaskReminder) {
        return mergeFrom((sw.Reminder.service2.TaskReminder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sw.Reminder.service2.TaskReminder other) {
      if (other == sw.Reminder.service2.TaskReminder.getDefaultInstance()) return this;
      if (!other.getDateTime().isEmpty()) {
        dateTime_ = other.dateTime_;
        onChanged();
      }
      if (!other.getTaskName().isEmpty()) {
        taskName_ = other.taskName_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sw.Reminder.service2.TaskReminder parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sw.Reminder.service2.TaskReminder) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dateTime_ = "";
    /**
     * <code>string date_time = 1;</code>
     */
    public java.lang.String getDateTime() {
      java.lang.Object ref = dateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date_time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateTimeBytes() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date_time = 1;</code>
     */
    public Builder setDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string date_time = 1;</code>
     */
    public Builder clearDateTime() {
      
      dateTime_ = getDefaultInstance().getDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string date_time = 1;</code>
     */
    public Builder setDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskName_ = "";
    /**
     * <code>string task_name = 2;</code>
     */
    public java.lang.String getTaskName() {
      java.lang.Object ref = taskName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskNameBytes() {
      java.lang.Object ref = taskName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_name = 2;</code>
     */
    public Builder setTaskName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_name = 2;</code>
     */
    public Builder clearTaskName() {
      
      taskName_ = getDefaultInstance().getTaskName();
      onChanged();
      return this;
    }
    /**
     * <code>string task_name = 2;</code>
     */
    public Builder setTaskNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskName_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.service2.Type type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.service2.Type type = 3;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.service2.Type type = 3;</code>
     */
    public sw.Reminder.service2.Type getType() {
      @SuppressWarnings("deprecation")
      sw.Reminder.service2.Type result = sw.Reminder.service2.Type.valueOf(type_);
      return result == null ? sw.Reminder.service2.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.service2.Type type = 3;</code>
     */
    public Builder setType(sw.Reminder.service2.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.service2.Type type = 3;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service2.TaskReminder)
  }

  // @@protoc_insertion_point(class_scope:service2.TaskReminder)
  private static final sw.Reminder.service2.TaskReminder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sw.Reminder.service2.TaskReminder();
  }

  public static sw.Reminder.service2.TaskReminder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskReminder>
      PARSER = new com.google.protobuf.AbstractParser<TaskReminder>() {
    @java.lang.Override
    public TaskReminder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskReminder(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskReminder> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskReminder> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sw.Reminder.service2.TaskReminder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

