// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package sw.Reminder.service2;

public interface TaskReminderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.TaskReminder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date_time = 1;</code>
   */
  java.lang.String getDateTime();
  /**
   * <code>string date_time = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <code>string task_name = 2;</code>
   */
  java.lang.String getTaskName();
  /**
   * <code>string task_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskNameBytes();

  /**
   * <code>.service2.Type type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.service2.Type type = 3;</code>
   */
  sw.Reminder.service2.Type getType();
}
