// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package sw.Reminder.service1;

public final class SmartWatchHealthImpl {
  private SmartWatchHealthImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_TaskReminder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_TaskReminder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_TaskComplete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_TaskComplete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\032\033google/proto" +
      "buf/empty.proto\"/\n\014TaskReminder\022\014\n\004time\030" +
      "\001 \001(\003\022\021\n\ttask_name\030\002 \001(\t\"#\n\016ServerRespon" +
      "se\022\021\n\tconfirmed\030\001 \001(\t\"4\n\014TaskComplete\022\021\n" +
      "\ttask_name\030\001 \001(\t\022\021\n\tcompleted\030\002 \001(\0102\243\002\n\010" +
      "Reminder\022E\n\017SetTaskReminder\022\026.service2.T" +
      "askReminder\032\030.service2.ServerResponse\"\000\022" +
      "E\n\rcheckReminder\022\026.google.protobuf.Empty" +
      "\032\030.service2.ServerResponse\"\0000\001\022F\n\020MarkTa" +
      "skComplete\022\026.service2.TaskComplete\032\030.ser" +
      "vice2.ServerResponse\"\000\022A\n\013GetTaskList\022\026." +
      "google.protobuf.Empty\032\026.service2.TaskRem" +
      "inder\"\0000\001B.\n\024sw.Reminder.service1B\024Smart" +
      "WatchHealthImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_service2_TaskReminder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_TaskReminder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_TaskReminder_descriptor,
        new java.lang.String[] { "Time", "TaskName", });
    internal_static_service2_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ServerResponse_descriptor,
        new java.lang.String[] { "Confirmed", });
    internal_static_service2_TaskComplete_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_TaskComplete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_TaskComplete_descriptor,
        new java.lang.String[] { "TaskName", "Completed", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
